### ISSUE TITLE
release 3.1 or 4.0?

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/stac-pydantic#141]
We've recently pushed some changes to main which are worth a new release 

https://github.com/stac-utils/stac-pydantic/blob/f68282688696bdad74944fa794fd004290c62fcb/CHANGELOG.txt#L1-L7

☝️ contains some `almost` breaking changes, but better match the specification so I'm not sure we want to go for a new Major version (cc @gadomski @jonhealy1) 

We also have #131 and #135 which should be merged before doing new releases.

**Comment by gadomski** [comment]
My instinct is to _not_ go breaking, at least based on that changelog -- the only one that might be breaking-ish is the enforcing the required type, but as you say that's just bringing in line w/ spec. I'm 👍🏼 for v3.1.0.
