### ISSUE TITLE
What's the purpose of this library?

### ISSUE THREAD

**Issue by mht2953658596** [stac-utils/stac-pydantic#160]
Is the purpose of this library to automatically convert some JSON files into Pydantic model classes?

**Comment by vincentsarago** [comment]
@mht2953658596 the main purpose of this library is described in the readme 👇  

> [Pydantic](https://pydantic-docs.helpmanual.io/) models for [STAC](https://github.com/radiantearth/stac-spec) Catalogs, Collections, Items, and the [STAC API](https://github.com/radiantearth/stac-api-spec) spec. Initially developed by [arturo-ai](https://github.com/arturo-ai).

> The main purpose of this library is to provide reusable request/response models for tools such as [fastapi](https://fastapi.tiangolo.com/). For more comprehensive schema validation and robust extension support, use [pystac](https://github.com/stac-utils/pystac).

ref: https://github.com/stac-utils/stac-pydantic?tab=readme-ov-file#stac-pydantic

We mainly use stac-pydantic model to validate STAC Items in FastAPI application
