### ISSUE TITLE
include microseconds when decoding datetime objects

### ISSUE THREAD

**Issue by geospatial-jeff** [stac-utils/stac-pydantic#76]
Thanks for reviewing and merging!

Good point on the serialization discrepancy. The major meaningful difference to me is that the sub-second portion of the datetime is discarded during serialization. But this probably doesn't matter most of the time.

Could be fixed by changing

https://github.com/stac-utils/stac-pydantic/blob/master/stac_pydantic/shared.py#L18

to include the [`%f` (microsecond) part](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes). 

```
DATETIME_RFC339 = "%Y-%m-%dT%H:%M:%S.%fZ"
```

_Originally posted by @colecloudtostreet in https://github.com/stac-utils/stac-pydantic/issues/75#issuecomment-843369648_

**Comment by philvarner** [comment]
Also, the constant for this should be `DATETIME_RFC3339` not `DATETIME_RFC339` (there are 3 3s, not 2).

**Comment by philvarner** [comment]
Another major meaningful difference is that this regex is used in the Search object, so datetimes with fractional seconds in them throw an error when used by pystac-client in a query.

**Comment by vincentsarago** [comment]
should be fixed now 🙏
