### ISSUE TITLE
error with null datetime

### ISSUE THREAD

**Issue by jonhealy1** [stac-utils/stac-pydantic#77]
I was looking at upgrading stac-pydantic and I noticed that it does not like: ``` "datetime": null ``` in a stac item. I got this error message running pytest as well. I think this line needs to be changed: https://github.com/stac-utils/stac-pydantic/blob/c2db77ca5d0ae1bf184092e3e76ab2946fb09183/stac_pydantic/item.py#L23

```
$ stac-pydantic validate-item https://raw.githubusercontent.com/radiantearth/stac-spec/master/examples/collectionless-item.json

1 validation error for CustomStacItem
properties -> datetime
  none is not an allowed value (type=type_error.none.not_allowed)
```
* To get this error you need to change the version to '1.0.0-rc.4' in version.py

**Comment by jonhealy1** [comment]
It says here that null is allowed for datetime: https://github.com/radiantearth/stac-spec/blob/v1.0.0-beta.2/item-spec/item-spec.md

**Comment by jonhealy1** [comment]
I tried this ``` datetime: Union[dt, str] = Field(None, alias="datetime") ``` but then this test fails `` test_validate_item_reraise_exception ``` because it is allowing an item with no datetime key whatsoever to pass.

**Comment by geospatial-jeff** [comment]
I think maybe we can update the ItemProperties.datetime type to 'Optional[datetime] = Field(...)'

The '...' indicates the field is required, so a user has to explicitely pass 'None'.  I don't have the pydantic docs in front of me (I'm on mobile atm) but I think this is how it works.

**Comment by jonhealy1** [comment]
Do you think that in ``` "datetime": null ```, the problem is that ``` null ``` should be ``` None ``` for Python?

**Comment by kylebarron** [comment]
A JSON `null` is equivalent to a Python `None`. When you call `json.load` on that JSON document, you'll get `'datetime': None`

**Comment by alukach** [comment]
I do believe that we should instead be expecting `None` rather than `"null"`. See #116 for a PR.
