### ISSUE TITLE
Add `Relation.items`

### ISSUE THREAD

**Issue by geospatial-jeff** [stac-utils/stac-pydantic#82]
https://github.com/stac-utils/stac-fastapi/pull/141

**Comment by lossyrob** [comment]
`Relation.item` is used in other contexts (links to individual items in a catalog/collection), so really we should also add `items`

**Comment by vincentsarago** [comment]
https://github.com/stac-utils/stac-pydantic/blob/7b1cb443bf55ae5968d9b0e889cb0ac84a92e5eb/stac_pydantic/links.py#L63
