### ISSUE TITLE
Upgrade to STAC 1.0

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/stac-pydantic#85]
Now that STAC 1.0 is released, we'll need to update stac-pydantic to handle the latest version.

The most major change is using URIs as extension IDs rather than their short names.

We can use this issue to collect all of the changes that need to be made to upgrade stac-pydantic for STAC 1.0.

**Comment by moradology** [comment]
With #86, this issue can now be closed

**Comment by lossyrob** [comment]
🎉
