### ISSUE TITLE
Release new version of stac-pydantic

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/stac-pydantic#91]
With STAC 1.0 support (#85) nearly closed out, we should prepare to release a new version.

@geospatial-jeff can you make the [stac-utils](https://pypi.org/user/stac-utils/) pypi user a co-maintainer of the stac-pydantic pypi repo? That way we can publish similar to stactools, pystac etc.

I can set up the GitHub actions to publish on new GitHub releases, and then make the release once everything is in for STAC 1.0.

**Comment by geospatial-jeff** [comment]
@lossyrob sent the invite to stac-utils pypi user.

**Comment by lossyrob** [comment]
@geospatial-jeff accepted!

Would this next release be `2.0.0`?

**Comment by lossyrob** [comment]
Released: https://pypi.org/project/stac-pydantic/2.0.0/
